// This file is auto-generated by scripts/sync-db.mjs
// DO NOT EDIT MANUALLY
export const snapshot: any = {
  "gallery": [
    {
      "_creationTime": 1770198906410.3108,
      "_id": "k57brc21143khadvtet5qqcazs80gqsd",
      "active": true,
      "displayOrder": 1,
      "image": "/kebab-out-min.jpg",
      "title": "Kebab Delicieux"
    },
    {
      "_creationTime": 1770198906410.311,
      "_id": "k5707ts8bj4xx75zxzq0vtps9x80gvts",
      "active": true,
      "displayOrder": 2,
      "image": "/durum-kebab-out-min.jpg",
      "title": "Durum Frais"
    },
    {
      "_creationTime": 1770198906410.3113,
      "_id": "k579wtvdgecezy5z0khm1z21vn80hdw2",
      "active": true,
      "displayOrder": 3,
      "image": "/salade-poulet-min.jpg",
      "title": "Salade Poulet"
    },
    {
      "_creationTime": 1770198906410.3115,
      "_id": "k573rg8ges0ka652ngfgk4052s80hwcf",
      "active": true,
      "displayOrder": 4,
      "image": "/kebabman-min-1.jpg",
      "title": "Notre Chef"
    },
    {
      "_creationTime": 1770198906410.3118,
      "_id": "k571mn2w13y6ndtna7b6x00cps80gppx",
      "active": true,
      "displayOrder": 5,
      "image": "/durum-man-out-min.jpg",
      "title": "Durum Special"
    },
    {
      "_creationTime": 1770198906410.312,
      "_id": "k571zaxzem13skx6dhc9sqymad80gnmw",
      "active": true,
      "displayOrder": 6,
      "image": "/durum-kebab-making-min.jpg",
      "title": "Durum"
    },
    {
      "_creationTime": 1771850453311.7808,
      "_id": "k57b75j1jxhc7kfqzqhtqf7gp581ph16",
      "active": true,
      "displayOrder": 1,
      "image": "/kebab-out-min.jpg",
      "title": "Kebab Delicieux"
    },
    {
      "_creationTime": 1771850453311.781,
      "_id": "k57f2s1wtabm9pr7ad128nezrx81p9ge",
      "active": true,
      "displayOrder": 2,
      "image": "/durum-kebab-out-min.jpg",
      "title": "Durum Frais"
    },
    {
      "_creationTime": 1771850453311.7812,
      "_id": "k57fecqqsw8q3gf4zw6jz06x8581pgb7",
      "active": true,
      "displayOrder": 3,
      "image": "/salade-poulet-min.jpg",
      "title": "Salade Poulet"
    },
    {
      "_creationTime": 1771850453311.7815,
      "_id": "k57by482sgyeznkg3wse145p8181p63h",
      "active": true,
      "displayOrder": 4,
      "image": "/kebabman-min-1.jpg",
      "title": "Notre Chef"
    },
    {
      "_creationTime": 1771850453311.7817,
      "_id": "k57fgyyr7dhg4vzj3wt7ebxxch81qe7t",
      "active": true,
      "displayOrder": 5,
      "image": "/durum-man-out-min.jpg",
      "title": "Durum Special"
    },
    {
      "_creationTime": 1771850453311.782,
      "_id": "k573sr74w33y1e3fzqyn1x39vn81q110",
      "active": true,
      "displayOrder": 6,
      "image": "/durum-kebab-making-min.jpg",
      "title": "Preparation Durum"
    }
  ],
  "menuCategories": [
    {
      "_creationTime": 1771850442326.8508,
      "_id": "jx79dnqxrj3v8d3451ycvq8wf581pcvn",
      "active": true,
      "displayOrder": 1,
      "name": "Sandwichs",
      "slug": "sandwiches"
    },
    {
      "_creationTime": 1771850442326.851,
      "_id": "jx79d97eprq1q0g00j0y54p6cn81p79y",
      "active": true,
      "displayOrder": 6,
      "name": "Sandwichs Végétarien",
      "slug": "sandwiches-vegetarien"
    },
    {
      "_creationTime": 1771850442326.8513,
      "_id": "jx74ny6gkrp6d1dq09ctjtbzy981qb3w",
      "active": true,
      "displayOrder": 6,
      "name": "Assiettes",
      "slug": "assiettes"
    },
    {
      "_creationTime": 1771850442326.8516,
      "_id": "jx7c50vqqptc4rjxp6bs4kk3g981p2zv",
      "active": true,
      "displayOrder": 3,
      "name": "Barquettes",
      "slug": "barquettes"
    },
    {
      "_creationTime": 1771850442326.8518,
      "_id": "jx7dm3fyjg2fnsyht7v3x987xd81p6vb",
      "active": true,
      "displayOrder": 4,
      "name": "Salades",
      "slug": "salades"
    },
    {
      "_creationTime": 1771850442326.852,
      "_id": "jx74rysypp0twyvgvz9kj0g35s81pgg8",
      "active": true,
      "displayOrder": 4,
      "name": "Pizzas",
      "slug": "pizzas"
    },
    {
      "_creationTime": 1771850442326.8523,
      "_id": "jx7376k3zp2x9hgptvf8s4xcq181qtcv",
      "active": true,
      "displayOrder": 2,
      "name": "Tacos",
      "slug": "tacos"
    },
    {
      "_creationTime": 1771850442326.8525,
      "_id": "jx73x8q2vwhd658cr1r473qf0n81qz5e",
      "active": true,
      "displayOrder": 3,
      "name": "Durum",
      "slug": "durum"
    },
    {
      "_creationTime": 1771850442326.8528,
      "_id": "jx7akmzn5kqt805r3rmh0bhd3h81p1hb",
      "active": true,
      "displayOrder": 8,
      "name": "Bowls",
      "slug": "bowls"
    },
    {
      "_creationTime": 1771850442326.853,
      "_id": "jx7ca0xm7kdz3gbqqh8p95vzsd81pqqz",
      "active": true,
      "displayOrder": 9,
      "name": "Kapsalon",
      "slug": "kapsalon"
    },
    {
      "_creationTime": 1771850442326.8533,
      "_id": "jx740edjsc70xwvbs1kgxs3grd81p52e",
      "active": true,
      "displayOrder": 10,
      "name": "Box",
      "slug": "box"
    },
    {
      "_creationTime": 1771850442326.8535,
      "_id": "jx7fxj5hbpxq3weq1ggw8xvpy581qszv",
      "active": true,
      "displayOrder": 11,
      "name": "Desserts",
      "slug": "desserts"
    },
    {
      "_creationTime": 1771850442326.8538,
      "_id": "jx716azf8k5mt1vw5q6ryaspk581qqre",
      "active": true,
      "displayOrder": 12,
      "name": "Boissons",
      "slug": "boissons"
    }
  ],
  "menuItemToppings": [
    {
      "_creationTime": 1771851854696.8838,
      "_id": "j574j253vb1wec0eq4s8fq4twx81qbz7",
      "displayOrder": 0,
      "menuItemId": "j971m9szjh4ftw1qap6qxgktmx81q3nr",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771851854696.884,
      "_id": "j5731brwx9ws8vvegn76ten30s81pf4t",
      "displayOrder": 1,
      "menuItemId": "j971m9szjh4ftw1qap6qxgktmx81q3nr",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771851854696.8843,
      "_id": "j5757xwc17zy5gpj5dykw1g0x981px4m",
      "displayOrder": 2,
      "menuItemId": "j971m9szjh4ftw1qap6qxgktmx81q3nr",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852184371.0457,
      "_id": "j571ct9f2zgygr7a5assh5tzrd81pm2t",
      "displayOrder": 0,
      "menuItemId": "j97dz0xxsf7a7cz5c7rt98bew981p98x",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852184371.046,
      "_id": "j57bzp4v5rjyw7bnea2sakj53h81q2jq",
      "displayOrder": 1,
      "menuItemId": "j97dz0xxsf7a7cz5c7rt98bew981p98x",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852184371.0461,
      "_id": "j57b14zet6ypqtb7rzc5fc9zwd81q3eb",
      "displayOrder": 2,
      "menuItemId": "j97dz0xxsf7a7cz5c7rt98bew981p98x",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852344134.669,
      "_id": "j57db7dbgsnr5cnyn74nrj5m5s81pgnk",
      "displayOrder": 0,
      "menuItemId": "j97ek9mj6mf3806ezmw5cnck6x81ptrm",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852344134.6692,
      "_id": "j578mpycvqjbpt92p5kt4t248h81qb3z",
      "displayOrder": 1,
      "menuItemId": "j97ek9mj6mf3806ezmw5cnck6x81ptrm",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852344134.6694,
      "_id": "j570hb8b4e2yvzvcc2k1ccjzj581pj43",
      "displayOrder": 2,
      "menuItemId": "j97ek9mj6mf3806ezmw5cnck6x81ptrm",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852349222.7485,
      "_id": "j576f2rj653rws1kry3xxsafm981qv82",
      "displayOrder": 0,
      "menuItemId": "j97fxfn2j6sh4e0s8b1mdtagtx81qazy",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852349222.7488,
      "_id": "j578tkkmvejrw1rc6jn5nvvz8n81q9am",
      "displayOrder": 1,
      "menuItemId": "j97fxfn2j6sh4e0s8b1mdtagtx81qazy",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852349222.749,
      "_id": "j574vq8crb5w1r5s5hvenhm9g981qgr3",
      "displayOrder": 2,
      "menuItemId": "j97fxfn2j6sh4e0s8b1mdtagtx81qazy",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852395660.9556,
      "_id": "j571gdy8z6ch69ehhty759rwch81qqtg",
      "displayOrder": 0,
      "menuItemId": "j974mwpb26ytszx1k9qn30vv5d81pvrc",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852395660.9558,
      "_id": "j576dawkxr0d26j9gg7g5n791181ptn5",
      "displayOrder": 1,
      "menuItemId": "j974mwpb26ytszx1k9qn30vv5d81pvrc",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852395660.956,
      "_id": "j57daddx5ewmzmrjx4akksf7dh81q646",
      "displayOrder": 2,
      "menuItemId": "j974mwpb26ytszx1k9qn30vv5d81pvrc",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852400433.7327,
      "_id": "j57ehqqx4vbbkdcyg3kd089yx581q4vy",
      "displayOrder": 0,
      "menuItemId": "j97dwagfzkqr9120n9bg86df4981q16h",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852400433.733,
      "_id": "j577jsd13x56ed68dammn1na4h81phj9",
      "displayOrder": 1,
      "menuItemId": "j97dwagfzkqr9120n9bg86df4981q16h",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852400433.7332,
      "_id": "j57d36f6aaywew7bec99hwqrp981q122",
      "displayOrder": 2,
      "menuItemId": "j97dwagfzkqr9120n9bg86df4981q16h",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852404756.1123,
      "_id": "j571drpnmchwmzb1r7btsnm0cd81q0mb",
      "displayOrder": 0,
      "menuItemId": "j97be1f9j49nwegv6jdmb9cj5d81qfd5",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852404756.1125,
      "_id": "j5706071jv2kjk793101yzxr1d81qc65",
      "displayOrder": 1,
      "menuItemId": "j97be1f9j49nwegv6jdmb9cj5d81qfd5",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852404756.1128,
      "_id": "j575w0tyda7xdbg4nw8jxy46hs81q111",
      "displayOrder": 2,
      "menuItemId": "j97be1f9j49nwegv6jdmb9cj5d81qfd5",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852409373.234,
      "_id": "j573rezfxyte8zn6mtbnak4vvs81qcjm",
      "displayOrder": 0,
      "menuItemId": "j97dwbte88hh85byxdjcjdc28181qge7",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852409373.2341,
      "_id": "j57atydz814rxjaqrzy2a25zrh81qpcd",
      "displayOrder": 1,
      "menuItemId": "j97dwbte88hh85byxdjcjdc28181qge7",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852409373.2344,
      "_id": "j57dfff70s8bh9409fvtn4s62s81qcqc",
      "displayOrder": 2,
      "menuItemId": "j97dwbte88hh85byxdjcjdc28181qge7",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852414378.984,
      "_id": "j57f6g8yscbtp5yw3hvcq4fqz181qych",
      "displayOrder": 0,
      "menuItemId": "j976c5eaegbk4ky4p73pz90w5s81pddd",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852414378.9841,
      "_id": "j5713a956t1yzyjcgk7rq7gzh981pf7a",
      "displayOrder": 1,
      "menuItemId": "j976c5eaegbk4ky4p73pz90w5s81pddd",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852414378.9844,
      "_id": "j57bg8k9enr0pbpacj2zzsya3x81pbdc",
      "displayOrder": 2,
      "menuItemId": "j976c5eaegbk4ky4p73pz90w5s81pddd",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852425025.393,
      "_id": "j574xhj03sc8kedb1t0394gbg981qrmf",
      "displayOrder": 0,
      "menuItemId": "j97cq7d3wejn9n9hhgnprb3t8181pgbx",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852425025.3933,
      "_id": "j57876fwn987b899jyrzdf1de181pchh",
      "displayOrder": 1,
      "menuItemId": "j97cq7d3wejn9n9hhgnprb3t8181pgbx",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852425025.3936,
      "_id": "j575tm27cqj5ezt388zx2c4axs81q6qd",
      "displayOrder": 2,
      "menuItemId": "j97cq7d3wejn9n9hhgnprb3t8181pgbx",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852429457.8887,
      "_id": "j57d3h8bedxastz8yp33f0rj4981qg3j",
      "displayOrder": 0,
      "menuItemId": "j97bmvr2x24zxz4rthq9ex4h4d81pypn",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852429457.889,
      "_id": "j578zkwdyb3hzvw1mdyn39hxy581qgh2",
      "displayOrder": 1,
      "menuItemId": "j97bmvr2x24zxz4rthq9ex4h4d81pypn",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852429457.8892,
      "_id": "j57928n1be1dq86dr2cgks786h81p9d1",
      "displayOrder": 2,
      "menuItemId": "j97bmvr2x24zxz4rthq9ex4h4d81pypn",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852534261.1138,
      "_id": "j574rbp6k1r898chkyrgf1v8dh81qyq8",
      "displayOrder": 0,
      "menuItemId": "j97f9fh7rjweyhf84n7r69rcgx81pvaf",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852534261.114,
      "_id": "j576s3c6s2ta4wcp26khg356tx81phxj",
      "displayOrder": 1,
      "menuItemId": "j97f9fh7rjweyhf84n7r69rcgx81pvaf",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852534261.1143,
      "_id": "j5798qnkaqtakwr93dazzdk4w581phv0",
      "displayOrder": 2,
      "menuItemId": "j97f9fh7rjweyhf84n7r69rcgx81pvaf",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852539024.2031,
      "_id": "j572p2vvn59m915snjbmx609zs81qa53",
      "displayOrder": 0,
      "menuItemId": "j975v4ktns043y1ayqc5t343hn81pjxf",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852539024.2034,
      "_id": "j57cjqm50xrnsn2a083krys6e981pg7e",
      "displayOrder": 1,
      "menuItemId": "j975v4ktns043y1ayqc5t343hn81pjxf",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852539024.2036,
      "_id": "j57fg2fvxbqnenwzqab2k28twn81pvag",
      "displayOrder": 2,
      "menuItemId": "j975v4ktns043y1ayqc5t343hn81pjxf",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852544081.6118,
      "_id": "j57dta85xbdwywcvsn09kqr20d81pzxa",
      "displayOrder": 0,
      "menuItemId": "j976tb7d2yfjr5ttnqt9pvtmts81qyed",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852544081.612,
      "_id": "j57c1c830qyj0dv3gwc6qp6b5n81pn0f",
      "displayOrder": 1,
      "menuItemId": "j976tb7d2yfjr5ttnqt9pvtmts81qyed",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852544081.6123,
      "_id": "j57a4e61t2h53c55xh5bajsp4s81q3y6",
      "displayOrder": 2,
      "menuItemId": "j976tb7d2yfjr5ttnqt9pvtmts81qyed",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852548227.7234,
      "_id": "j574stfmywm6nzmgvgz15mndcn81q6pa",
      "displayOrder": 0,
      "menuItemId": "j97cx2k1ytdq21jehrkk45fd0181pgyj",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852548227.7236,
      "_id": "j57b0kwfx9qfqptedqft87vwe181pkz1",
      "displayOrder": 1,
      "menuItemId": "j97cx2k1ytdq21jehrkk45fd0181pgyj",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852548227.7239,
      "_id": "j57e6xxm228vjk1a6c1n0q0h6n81pm2s",
      "displayOrder": 2,
      "menuItemId": "j97cx2k1ytdq21jehrkk45fd0181pgyj",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852553258.738,
      "_id": "j573b2x77kcnqjcbewexv33pnh81q56s",
      "displayOrder": 0,
      "menuItemId": "j9769640fr7rg39zfxn958e75n81pe0j",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852553258.7383,
      "_id": "j578gsxdqd4x3h3qeby59wtk3181p5mp",
      "displayOrder": 1,
      "menuItemId": "j9769640fr7rg39zfxn958e75n81pe0j",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852553258.7385,
      "_id": "j575c0vhep9p6eqp870qjhykgd81qhsk",
      "displayOrder": 2,
      "menuItemId": "j9769640fr7rg39zfxn958e75n81pe0j",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852561182.5928,
      "_id": "j57ep8hd3s8rz7md16jdx1xbz181prg6",
      "displayOrder": 0,
      "menuItemId": "j97drerc2xfzj23m7z80hckj2n81qa8s",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852561182.593,
      "_id": "j57e7mw92gzvm65z4tzp80ts3x81pcam",
      "displayOrder": 1,
      "menuItemId": "j97drerc2xfzj23m7z80hckj2n81qa8s",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852561182.5933,
      "_id": "j576dxzmwfn78fw1tvzgha9db981qade",
      "displayOrder": 2,
      "menuItemId": "j97drerc2xfzj23m7z80hckj2n81qa8s",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852566128.283,
      "_id": "j571vvv0xavpmbf5ypz5tfy59981pc9m",
      "displayOrder": 0,
      "menuItemId": "j975xfmpesj85qbkrbwnb27w6s81pwvb",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852566128.2832,
      "_id": "j57aafn91ht4chrqcarqf4w62n81qcpn",
      "displayOrder": 1,
      "menuItemId": "j975xfmpesj85qbkrbwnb27w6s81pwvb",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852566128.2834,
      "_id": "j57cydh5chztrzmzn6es9evhwn81p2tf",
      "displayOrder": 2,
      "menuItemId": "j975xfmpesj85qbkrbwnb27w6s81pwvb",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852571021.5474,
      "_id": "j579cc4gyd991dnzybbpmtx0yd81p6xt",
      "displayOrder": 0,
      "menuItemId": "j9759be9epekvy11vzj1ajsv8x81p8hx",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852571021.5476,
      "_id": "j57fae442tmfepemtfvby3e16h81pss1",
      "displayOrder": 1,
      "menuItemId": "j9759be9epekvy11vzj1ajsv8x81p8hx",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852571021.5479,
      "_id": "j578ftsrx33a7tfh977gekw2c981pwer",
      "displayOrder": 2,
      "menuItemId": "j9759be9epekvy11vzj1ajsv8x81p8hx",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852575157.8994,
      "_id": "j578fs561yet6pq8zhhjd0dgtn81pxr4",
      "displayOrder": 0,
      "menuItemId": "j9721tnew3d74v0wshf1skxxqn81phq9",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852575157.8997,
      "_id": "j57dr6abdcxp6t8f65n5pdq0td81qtgr",
      "displayOrder": 1,
      "menuItemId": "j9721tnew3d74v0wshf1skxxqn81phq9",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852575157.9,
      "_id": "j57b3byrcss55r5qjjtnbsc3ws81pbsz",
      "displayOrder": 2,
      "menuItemId": "j9721tnew3d74v0wshf1skxxqn81phq9",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852621135.5027,
      "_id": "j57fjjm3jraxfbt4mh1xj9k5bx81pbxp",
      "displayOrder": 0,
      "menuItemId": "j971zyf8dr8w0x4pynghc2yw8181p9re",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852621135.503,
      "_id": "j57asge9bs5m3z0mkddqv5y6qx81p2am",
      "displayOrder": 1,
      "menuItemId": "j971zyf8dr8w0x4pynghc2yw8181p9re",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852621135.5032,
      "_id": "j574kb641m6temp5cgcrcwzm1h81pm9g",
      "displayOrder": 2,
      "menuItemId": "j971zyf8dr8w0x4pynghc2yw8181p9re",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852626351.2932,
      "_id": "j57ccb4s0nsp6mwhp1g455zc3n81q1jg",
      "displayOrder": 0,
      "menuItemId": "j97ca86sqsgknsetm1y0ds3gq181pkvb",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852626351.2935,
      "_id": "j57av70n395hdefyct4hncq23581q47x",
      "displayOrder": 1,
      "menuItemId": "j97ca86sqsgknsetm1y0ds3gq181pkvb",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852626351.2937,
      "_id": "j576w4dn7cqgw20eeqh74veys181qt7e",
      "displayOrder": 2,
      "menuItemId": "j97ca86sqsgknsetm1y0ds3gq181pkvb",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852630780.6316,
      "_id": "j5700z0twga0mbhg8zmry5es0s81qwr9",
      "displayOrder": 0,
      "menuItemId": "j97bn1ashana3t9zywsvgm7djx81q5h2",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852630780.6318,
      "_id": "j57ay9s8smqddhnd39148rh8gs81pf3a",
      "displayOrder": 1,
      "menuItemId": "j97bn1ashana3t9zywsvgm7djx81q5h2",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852630780.632,
      "_id": "j576dnphw75c026wr72wcjzg6181pqbt",
      "displayOrder": 2,
      "menuItemId": "j97bn1ashana3t9zywsvgm7djx81q5h2",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852635871.289,
      "_id": "j57f7ytx0hv8tgvgfxpyjcfvkh81qv4d",
      "displayOrder": 0,
      "menuItemId": "j975nxb9trjnx61228fbd68s2n81qgzj",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852635871.2893,
      "_id": "j570a8fydfa49v5nj6xfv5at7981p0x9",
      "displayOrder": 1,
      "menuItemId": "j975nxb9trjnx61228fbd68s2n81qgzj",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852635871.2896,
      "_id": "j577n6hwdzejbbk3z8fjxhsz4x81q47q",
      "displayOrder": 2,
      "menuItemId": "j975nxb9trjnx61228fbd68s2n81qgzj",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852640503.4883,
      "_id": "j575wahzcdkznxr4f9sqwvw6zx81pbvf",
      "displayOrder": 0,
      "menuItemId": "j97am3sxc6hwtj10ww2vt75xk581q5b8",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852640503.4885,
      "_id": "j5724xmv0xrsdxg56d4ee2g06s81pa2f",
      "displayOrder": 1,
      "menuItemId": "j97am3sxc6hwtj10ww2vt75xk581q5b8",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852640503.4888,
      "_id": "j573j9pqyhrqhdcwwwpc12eyyx81qqr3",
      "displayOrder": 2,
      "menuItemId": "j97am3sxc6hwtj10ww2vt75xk581q5b8",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852645621.4805,
      "_id": "j570x9d43k577t5hb05j9q6nyh81qfrx",
      "displayOrder": 0,
      "menuItemId": "j977cjvjmg8zy4s7j4w9dmkh3n81pas9",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852645621.4807,
      "_id": "j57ey8gnfvw5r6tz9kh02gsjv581pee4",
      "displayOrder": 1,
      "menuItemId": "j977cjvjmg8zy4s7j4w9dmkh3n81pas9",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852645621.481,
      "_id": "j5778fv1sjsgkncmrwgmtcb0bs81pwvz",
      "displayOrder": 2,
      "menuItemId": "j977cjvjmg8zy4s7j4w9dmkh3n81pas9",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852651514.1235,
      "_id": "j5761zw8ettb5ybj2mbymf28as81pt2z",
      "displayOrder": 0,
      "menuItemId": "j976b5zcamrweyzvmjbyh81fzn81qscd",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852651514.1238,
      "_id": "j57735qzgyd477ccap304nfe9581phm3",
      "displayOrder": 1,
      "menuItemId": "j976b5zcamrweyzvmjbyh81fzn81qscd",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852651514.124,
      "_id": "j577bcj89s9kpkastzngc075ws81qkpy",
      "displayOrder": 2,
      "menuItemId": "j976b5zcamrweyzvmjbyh81fzn81qscd",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852656440.6858,
      "_id": "j571pepv2c9mjm9vtx0xewgz5581p7h0",
      "displayOrder": 0,
      "menuItemId": "j973pa33qx2t7h3zq6y5eg9avs81p41b",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852656440.686,
      "_id": "j578376zph8fw2swwk7k5gx1b981pchf",
      "displayOrder": 1,
      "menuItemId": "j973pa33qx2t7h3zq6y5eg9avs81p41b",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852656440.6863,
      "_id": "j572aesg7hcr5881nhh2gdtec981qc0g",
      "displayOrder": 2,
      "menuItemId": "j973pa33qx2t7h3zq6y5eg9avs81p41b",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852661201.1553,
      "_id": "j57cw3ff9191h0772k5st5p5f181qz1w",
      "displayOrder": 0,
      "menuItemId": "j97fw6gzpbcpv58jambth1yhgs81p4tg",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852661201.1555,
      "_id": "j572bkb96c8pa5272srmkpvp2x81qr8e",
      "displayOrder": 1,
      "menuItemId": "j97fw6gzpbcpv58jambth1yhgs81p4tg",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852661201.1558,
      "_id": "j573gkjw67nnvr4aqppmtqya0h81qwyf",
      "displayOrder": 2,
      "menuItemId": "j97fw6gzpbcpv58jambth1yhgs81p4tg",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852667074.8442,
      "_id": "j57fgveq1a2e2nbvwvws5a3s8s81q79b",
      "displayOrder": 0,
      "menuItemId": "j975xdk7ak1trf26e0bd2jbreh81q5ww",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852667074.8445,
      "_id": "j57d2x0vzefrfw4p9370ha1t0581pmjw",
      "displayOrder": 1,
      "menuItemId": "j975xdk7ak1trf26e0bd2jbreh81q5ww",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852667074.8447,
      "_id": "j57f2dk8j9eehqt42gnjxgzp6981paqf",
      "displayOrder": 2,
      "menuItemId": "j975xdk7ak1trf26e0bd2jbreh81q5ww",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852676188.6658,
      "_id": "j576kzed13n6vfbjjb2x02q2nh81qjnr",
      "displayOrder": 0,
      "menuItemId": "j971rf50nre3s548p5tefw6r1581pgp4",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852680095.6238,
      "_id": "j57b9n2yp0v3yaeqq5w6eybr8d81p8e1",
      "displayOrder": 0,
      "menuItemId": "j9729rkr40dtvps6knn39rqvkd81pscz",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852684217.592,
      "_id": "j57cf4dtgantt8jkyfwtd44ag981qpab",
      "displayOrder": 0,
      "menuItemId": "j97ept9r9k6n4mwmd3558by88d81qt8p",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852687878.1912,
      "_id": "j5720m68p0tsqmrbmtqtmyq6z581pe2b",
      "displayOrder": 0,
      "menuItemId": "j97238301skaredxffksvbptv981qryh",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852711466.5703,
      "_id": "j57f73tbtnc8kza7tzm45tyd0s81qm3m",
      "displayOrder": 0,
      "menuItemId": "j97f35ctbd9ka3xbf9070dtpw981q888",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852717592.8796,
      "_id": "j576v5ta6s0kapn7c363k3g13181pma0",
      "displayOrder": 0,
      "menuItemId": "j97djxsvyxvq6rkwenbr5kqh2n81qdte",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852724062.0854,
      "_id": "j5782bxttzfze79zk5tyb1txqn81pm8m",
      "displayOrder": 0,
      "menuItemId": "j97d8799btn6twbm1vc481yxwh81qcbw",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852728976.2087,
      "_id": "j57bz0fq56k0xx52mqxa6ekfxs81qka5",
      "displayOrder": 0,
      "menuItemId": "j970693jp5nk8mnktkbc4j5gy181q3bf",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852741538.088,
      "_id": "j571r47f06f6m9g3kentemw0n581p040",
      "displayOrder": 0,
      "menuItemId": "j97b0ebcp5agn8z1d3ycvqmf6h81p1ht",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852741538.0881,
      "_id": "j5776yf48wms1gmcr8bksx760n81pq4n",
      "displayOrder": 1,
      "menuItemId": "j97b0ebcp5agn8z1d3ycvqmf6h81p1ht",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852741538.0884,
      "_id": "j574ja9r3gwa3c8wcnyrpd7k6981pz1t",
      "displayOrder": 2,
      "menuItemId": "j97b0ebcp5agn8z1d3ycvqmf6h81p1ht",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852746458.701,
      "_id": "j57c85rh7ncpe36c43ckyvhs0181qtkb",
      "displayOrder": 0,
      "menuItemId": "j9733704ty03nbwqmbadq7g9j181pyrf",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852746458.7012,
      "_id": "j57anzx1eavvpvddcee0zw0ejn81pcwn",
      "displayOrder": 1,
      "menuItemId": "j9733704ty03nbwqmbadq7g9j181pyrf",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852746458.7014,
      "_id": "j57bvsvdrp2sm6p4c8dv4qg67981qtp2",
      "displayOrder": 2,
      "menuItemId": "j9733704ty03nbwqmbadq7g9j181pyrf",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852750122.788,
      "_id": "j571b8pqz1rc3gq2hgm8pjmwqd81q191",
      "displayOrder": 0,
      "menuItemId": "j975jkp7zevccnwgbhy7gtb8r581qybm",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852750122.7883,
      "_id": "j57fwtbsc6jtr9fv4579pwt4vn81q6p4",
      "displayOrder": 1,
      "menuItemId": "j975jkp7zevccnwgbhy7gtb8r581qybm",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852750122.7886,
      "_id": "j573n90zeb7gh4nxfvmqkym9nh81qvk7",
      "displayOrder": 2,
      "menuItemId": "j975jkp7zevccnwgbhy7gtb8r581qybm",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852760639.9226,
      "_id": "j572nmydjjm1ks3xq4je2x9mp181qra5",
      "displayOrder": 0,
      "menuItemId": "j97efxd3r3w1f3f14d0qv6h73n81qhkc",
      "toppingCategoryId": "viandes"
    },
    {
      "_creationTime": 1771852760639.9229,
      "_id": "j579jbtjcnk64phrcpa73nr5gn81qvhk",
      "displayOrder": 1,
      "menuItemId": "j97efxd3r3w1f3f14d0qv6h73n81qhkc",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852760639.923,
      "_id": "j578593wakwg3ae59p0fchnfth81pd33",
      "displayOrder": 2,
      "menuItemId": "j97efxd3r3w1f3f14d0qv6h73n81qhkc",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852765688.1245,
      "_id": "j57798h0m1grqatyy27b8fz4j581qytj",
      "displayOrder": 0,
      "menuItemId": "j97fw864y5cs89bxhzr16b6dxd81p8wc",
      "toppingCategoryId": "viandes"
    },
    {
      "_creationTime": 1771852765688.1248,
      "_id": "j574h8d8ksb1v8njp1hsy80ztn81p1n7",
      "displayOrder": 1,
      "menuItemId": "j97fw864y5cs89bxhzr16b6dxd81p8wc",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852765688.125,
      "_id": "j577akrdpjr33ew9vh864vmx8s81qms8",
      "displayOrder": 2,
      "menuItemId": "j97fw864y5cs89bxhzr16b6dxd81p8wc",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852769351.1494,
      "_id": "j57a0tc9070jje3hj3eqhj93rs81p1zb",
      "displayOrder": 0,
      "menuItemId": "j970myfg5cezwy64p3f57s1fn181qq5s",
      "toppingCategoryId": "viandes"
    },
    {
      "_creationTime": 1771852769351.1497,
      "_id": "j57fc3n7jaxdwq6r569ezk8bah81paam",
      "displayOrder": 1,
      "menuItemId": "j970myfg5cezwy64p3f57s1fn181qq5s",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852769351.15,
      "_id": "j573452c7fewxw128cr1ra4aex81q35v",
      "displayOrder": 2,
      "menuItemId": "j970myfg5cezwy64p3f57s1fn181qq5s",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852777624.1985,
      "_id": "j57efexx9zj94fn529v5vmjes981p85g",
      "displayOrder": 0,
      "menuItemId": "j97cy6gssg4ehq5nz896h3djzs81pjzb",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852777624.1987,
      "_id": "j576ca3cdtdg4hrd2qez09643181q1a5",
      "displayOrder": 1,
      "menuItemId": "j97cy6gssg4ehq5nz896h3djzs81pjzb",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852777624.199,
      "_id": "j578h926jmv5m2zdncgkdy46wn81pfq7",
      "displayOrder": 2,
      "menuItemId": "j97cy6gssg4ehq5nz896h3djzs81pjzb",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852782444.9202,
      "_id": "j574gphzk67dbtw7cwd7wshbjh81qf8w",
      "displayOrder": 0,
      "menuItemId": "j97fqwqm69pzqd11z21amjsgqd81qxdn",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852782444.9204,
      "_id": "j578trm0tbdda3ew84jhk0x0b181p7d8",
      "displayOrder": 1,
      "menuItemId": "j97fqwqm69pzqd11z21amjsgqd81qxdn",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852782444.9207,
      "_id": "j571w5p4mmfrafrh9zjga71kvd81pfjt",
      "displayOrder": 2,
      "menuItemId": "j97fqwqm69pzqd11z21amjsgqd81qxdn",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852786783.0159,
      "_id": "j574zwash59beb82ke3zjrybq581q9hb",
      "displayOrder": 0,
      "menuItemId": "j97b5km7n2n5fyv3mb6kys3ghh81psy4",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852786783.016,
      "_id": "j5771xf78f1798bndzs4qae42x81pnbm",
      "displayOrder": 1,
      "menuItemId": "j97b5km7n2n5fyv3mb6kys3ghh81psy4",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852786783.0164,
      "_id": "j5784n18ta146sf8snrm22hy7981pbfh",
      "displayOrder": 2,
      "menuItemId": "j97b5km7n2n5fyv3mb6kys3ghh81psy4",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852796223.4243,
      "_id": "j5722h7jmfccnyvfxrqcqdgkzx81qzvr",
      "displayOrder": 0,
      "menuItemId": "j976c9arsr7xbxb2ztbtta3dmn81qcv7",
      "toppingCategoryId": "viandes"
    },
    {
      "_creationTime": 1771852796223.4246,
      "_id": "j5786xmtgvcn3rzhdwakxqr9v581qs7p",
      "displayOrder": 1,
      "menuItemId": "j976c9arsr7xbxb2ztbtta3dmn81qcv7",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852796223.4248,
      "_id": "j578gd8rm6ve68awq8fp2bgqys81pjrn",
      "displayOrder": 2,
      "menuItemId": "j976c9arsr7xbxb2ztbtta3dmn81qcv7",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852796223.425,
      "_id": "j578kcdbsjsywt4acsfdctyndh81qn5x",
      "displayOrder": 3,
      "menuItemId": "j976c9arsr7xbxb2ztbtta3dmn81qcv7",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852799658.701,
      "_id": "j575f0g47ftwxeasq4ee46ttx181pjwg",
      "displayOrder": 0,
      "menuItemId": "j977yz3m02rsa6awk3jmee8apx81pcxs",
      "toppingCategoryId": "viandes"
    },
    {
      "_creationTime": 1771852799658.7012,
      "_id": "j570mfkb00cm2j50e94hpjwvtx81qmhq",
      "displayOrder": 1,
      "menuItemId": "j977yz3m02rsa6awk3jmee8apx81pcxs",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852799658.7014,
      "_id": "j573z4z7a2w2v7yn95yt9yy8an81pbhd",
      "displayOrder": 2,
      "menuItemId": "j977yz3m02rsa6awk3jmee8apx81pcxs",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852799658.7017,
      "_id": "j57d5gycs93fq8zhh8srwpavdh81qdbg",
      "displayOrder": 3,
      "menuItemId": "j977yz3m02rsa6awk3jmee8apx81pcxs",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852878820.6917,
      "_id": "j572xzw0wkqn90q7rpe3rszg5n81qa51",
      "displayOrder": 0,
      "menuItemId": "j972r9ag676np7yqzf81mvyzyn81prz9",
      "toppingCategoryId": "viandes"
    },
    {
      "_creationTime": 1771852878820.692,
      "_id": "j572fc206bcft4j51yxs5wkq0981q1n2",
      "displayOrder": 1,
      "menuItemId": "j972r9ag676np7yqzf81mvyzyn81prz9",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852878820.6921,
      "_id": "j578g7fzhgrjza5keqfjw9hwyh81p3f7",
      "displayOrder": 2,
      "menuItemId": "j972r9ag676np7yqzf81mvyzyn81prz9",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852878820.6924,
      "_id": "j5711vwbvkj5d6y1epe5xbz71x81ppkf",
      "displayOrder": 3,
      "menuItemId": "j972r9ag676np7yqzf81mvyzyn81prz9",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852883431.4778,
      "_id": "j572ywr0y277caeh74xtvmyefh81p673",
      "displayOrder": 0,
      "menuItemId": "j974yqz7syfw6hxcbbcq4tbznn81pfqn",
      "toppingCategoryId": "viandes"
    },
    {
      "_creationTime": 1771852883431.478,
      "_id": "j5760mjejm8fn9pmb8z59y68t181qqre",
      "displayOrder": 1,
      "menuItemId": "j974yqz7syfw6hxcbbcq4tbznn81pfqn",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852883431.4783,
      "_id": "j57fpr2g61ctep64c1e37fyfy981qc3b",
      "displayOrder": 2,
      "menuItemId": "j974yqz7syfw6hxcbbcq4tbznn81pfqn",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852883431.4785,
      "_id": "j57avs5cwh43z34s06nr7z0jcs81qejy",
      "displayOrder": 3,
      "menuItemId": "j974yqz7syfw6hxcbbcq4tbznn81pfqn",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852894977.7246,
      "_id": "j57705vkac6rb1q2hzhgwyhcsd81q0qa",
      "displayOrder": 0,
      "menuItemId": "j970831vykk6dn3bf13e1x4qkd81qpef",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852894977.7249,
      "_id": "j5781b0t1qm5v5y4me2d1qx42d81qjn5",
      "displayOrder": 1,
      "menuItemId": "j970831vykk6dn3bf13e1x4qkd81qpef",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852894977.725,
      "_id": "j575pjxm6ekd0yxgnfgv8rd58981p02b",
      "displayOrder": 2,
      "menuItemId": "j970831vykk6dn3bf13e1x4qkd81qpef",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771852899159.8635,
      "_id": "j575avwq7jrdvjky5mfh3y1tc181q9ej",
      "displayOrder": 0,
      "menuItemId": "j9738n2pn3w64nan36mnk7nn0x81pjhp",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771852899159.8638,
      "_id": "j572hxmt36qt4z6vsw7vrdt62s81qw11",
      "displayOrder": 1,
      "menuItemId": "j9738n2pn3w64nan36mnk7nn0x81pjhp",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771852899159.864,
      "_id": "j575h8870mkw8s7fs3rhzq4xsx81qbft",
      "displayOrder": 2,
      "menuItemId": "j9738n2pn3w64nan36mnk7nn0x81pjhp",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771853795921.1826,
      "_id": "j574v5ft8kmqf2ctr9v6dmf3j581qm4n",
      "displayOrder": 0,
      "menuItemId": "j9755ne2kt0b1pdb49w54k1hk581q266",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771853795921.1829,
      "_id": "j574w7nr1jw11eqjvj1sy0660d81qdef",
      "displayOrder": 1,
      "menuItemId": "j9755ne2kt0b1pdb49w54k1hk581q266",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771853795921.183,
      "_id": "j571mn3te72gnd4ae7q57cjcvs81pfpw",
      "displayOrder": 2,
      "menuItemId": "j9755ne2kt0b1pdb49w54k1hk581q266",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771853805263.9902,
      "_id": "j5748apdfxq5pvhqw87eddt3ps81qy2x",
      "displayOrder": 0,
      "menuItemId": "j974bqpppxzn4d7eqr3436r95181qfx1",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771853805263.9905,
      "_id": "j57853rhmjnwk7wwm5b9majnwh81qcr7",
      "displayOrder": 1,
      "menuItemId": "j974bqpppxzn4d7eqr3436r95181qfx1",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771853805263.9907,
      "_id": "j5749a1d91hgbf7z1tesvt4yr981pqha",
      "displayOrder": 2,
      "menuItemId": "j974bqpppxzn4d7eqr3436r95181qfx1",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771853810769.5017,
      "_id": "j573j454qynt1ndyx5r0t98r7n81qd50",
      "displayOrder": 0,
      "menuItemId": "j97da2cwb3bh7vzzxz6q348nzs81qhgj",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771853810769.502,
      "_id": "j57135eq27gqsge46z3tveq74581p9xb",
      "displayOrder": 1,
      "menuItemId": "j97da2cwb3bh7vzzxz6q348nzs81qhgj",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771853810769.5022,
      "_id": "j5790v4xmp1t4mbnjahvc6hr5n81qqfs",
      "displayOrder": 2,
      "menuItemId": "j97da2cwb3bh7vzzxz6q348nzs81qhgj",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771853815022.177,
      "_id": "j57b9237eg1frtqchrnyx7jk7h81q2bw",
      "displayOrder": 0,
      "menuItemId": "j97cb44z7rrs8q1j0qbxercmg981qymn",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771853815022.1772,
      "_id": "j575nhj5mdbjn55980wq9rbv5h81q18s",
      "displayOrder": 1,
      "menuItemId": "j97cb44z7rrs8q1j0qbxercmg981qymn",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771853815022.1775,
      "_id": "j5722msgnrxbw1pk9y4bmyv1qn81q5xn",
      "displayOrder": 2,
      "menuItemId": "j97cb44z7rrs8q1j0qbxercmg981qymn",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771853818867.0066,
      "_id": "j570pas7fzfewmwkrvvjf6e17981pm3t",
      "displayOrder": 0,
      "menuItemId": "j978ys24jq1dv8ztn5ev7c6n0581q4pd",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771853818867.0068,
      "_id": "j575xy4hb80dpg9td6mw7nq7m181p4s3",
      "displayOrder": 1,
      "menuItemId": "j978ys24jq1dv8ztn5ev7c6n0581q4pd",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771853818867.007,
      "_id": "j57ctbyjf5k5gy46ybyx19fqd581p4fe",
      "displayOrder": 2,
      "menuItemId": "j978ys24jq1dv8ztn5ev7c6n0581q4pd",
      "toppingCategoryId": "supplements"
    },
    {
      "_creationTime": 1771853833798.8306,
      "_id": "j5716txbq3dv5knj9wp5x3xh2181pr8s",
      "displayOrder": 0,
      "menuItemId": "j97anaxfadynaa1ba4btb5gpdd81qtxz",
      "toppingCategoryId": "sauces"
    },
    {
      "_creationTime": 1771853833798.8308,
      "_id": "j577aerh1tvyaa0mp86k51ytnd81qvjp",
      "displayOrder": 1,
      "menuItemId": "j97anaxfadynaa1ba4btb5gpdd81qtxz",
      "toppingCategoryId": "crudites"
    },
    {
      "_creationTime": 1771853833798.831,
      "_id": "j570y5htjwkkp9g522nse15nss81q9hv",
      "displayOrder": 2,
      "menuItemId": "j97anaxfadynaa1ba4btb5gpdd81qtxz",
      "toppingCategoryId": "supplements"
    }
  ],
  "menuItems": [
    {
      "_creationTime": 1771850446637.1238,
      "_id": "j97dz0xxsf7a7cz5c7rt98bew981p98x",
      "active": true,
      "categories": [
        "sandwiches"
      ],
      "categoryOrders": [],
      "description": "Pain frais, viande kebab, crudites et sauce au choix",
      "displayOrder": 0,
      "image": "",
      "name": "Sandwich Kebab",
      "popular": true,
      "price": 7,
      "priceWithFries": 9
    },
    {
      "_creationTime": 1771850446637.124,
      "_id": "j97ek9mj6mf3806ezmw5cnck6x81ptrm",
      "active": true,
      "categories": [
        "sandwiches"
      ],
      "categoryOrders": [],
      "description": "Version XXL de notre kebab classique avec double viande",
      "displayOrder": 1,
      "image": "",
      "name": "Maxi Kebab",
      "popular": true,
      "price": 10,
      "priceWithFries": 12
    },
    {
      "_creationTime": 1771850446637.1243,
      "_id": "j97fxfn2j6sh4e0s8b1mdtagtx81qazy",
      "active": true,
      "categories": [
        "sandwiches"
      ],
      "categoryOrders": [],
      "description": "Sandwich merguez grillees, salade, tomates, oignons",
      "displayOrder": 2,
      "image": "",
      "name": "Merguez",
      "popular": false,
      "price": 7,
      "priceWithFries": 9
    },
    {
      "_creationTime": 1771850446637.1245,
      "_id": "j9755ne2kt0b1pdb49w54k1hk581q266",
      "active": true,
      "categories": [
        "sandwiches"
      ],
      "categoryOrders": [],
      "description": "",
      "displayOrder": 3,
      "image": "",
      "name": "Saucisse Turque",
      "popular": false,
      "price": 7,
      "priceWithFries": 9
    },
    {
      "_creationTime": 1771850446637.1248,
      "_id": "j974bqpppxzn4d7eqr3436r95181qfx1",
      "active": true,
      "categories": [
        "sandwiches"
      ],
      "categoryOrders": [],
      "description": "",
      "displayOrder": 4,
      "image": "",
      "name": "Saucisse blanche",
      "popular": false,
      "price": 6.5,
      "priceWithFries": 8.5
    },
    {
      "_creationTime": 1771850446637.125,
      "_id": "j97da2cwb3bh7vzzxz6q348nzs81qhgj",
      "active": true,
      "categories": [
        "sandwiches"
      ],
      "categoryOrders": [],
      "description": "",
      "displayOrder": 5,
      "image": "",
      "name": "Köfte",
      "popular": false,
      "price": 7,
      "priceWithFries": 9
    },
    {
      "_creationTime": 1771850446637.1252,
      "_id": "j97cb44z7rrs8q1j0qbxercmg981qymn",
      "active": true,
      "categories": [
        "sandwiches"
      ],
      "categoryOrders": [],
      "description": "",
      "displayOrder": 6,
      "image": "",
      "name": "Spécial Köfte",
      "popular": false,
      "price": 8.5,
      "priceWithFries": 10.5
    },
    {
      "_creationTime": 1771850446637.1255,
      "_id": "j978ys24jq1dv8ztn5ev7c6n0581q4pd",
      "active": true,
      "categories": [
        "sandwiches"
      ],
      "categoryOrders": [],
      "description": "",
      "displayOrder": 7,
      "image": "",
      "name": "Adana",
      "popular": false,
      "price": 7.5,
      "priceWithFries": 9.5
    },
    {
      "_creationTime": 1771850446637.1257,
      "_id": "j97anaxfadynaa1ba4btb5gpdd81qtxz",
      "active": true,
      "categories": [
        "sandwiches"
      ],
      "categoryOrders": [],
      "description": "Melange kebab et poulet, double plaisir",
      "displayOrder": 8,
      "image": "",
      "name": "Sandwich Mixte",
      "popular": true,
      "price": 9,
      "priceWithFries": 11
    },
    {
      "_creationTime": 1771850446637.126,
      "_id": "j97cq7d3wejn9n9hhgnprb3t8181pgbx",
      "active": true,
      "categories": [
        "sandwiches"
      ],
      "categoryOrders": [],
      "description": "Pain brioche, steak hache, crudites et sauce",
      "displayOrder": 9,
      "image": "",
      "name": "Hamburger",
      "popular": false,
      "price": 6.5,
      "priceWithFries": 8.5
    },
    {
      "_creationTime": 1771850446637.1262,
      "_id": "j974mwpb26ytszx1k9qn30vv5d81pvrc",
      "active": true,
      "categories": [
        "sandwiches"
      ],
      "categoryOrders": [],
      "description": "Hamburger avec fromage fondu",
      "displayOrder": 10,
      "image": "",
      "name": "Cheesburger",
      "popular": false,
      "price": 7,
      "priceWithFries": 9
    },
    {
      "_creationTime": 1771850446637.1265,
      "_id": "j97bmvr2x24zxz4rthq9ex4h4d81pypn",
      "active": true,
      "categories": [
        "sandwiches"
      ],
      "categoryOrders": [],
      "description": "Filet de poisson pane, salade et sauce",
      "displayOrder": 11,
      "image": "",
      "name": "Fish",
      "popular": false,
      "price": 6.5,
      "priceWithFries": 8.5
    },
    {
      "_creationTime": 1771850446637.1267,
      "_id": "j976c5eaegbk4ky4p73pz90w5s81pddd",
      "active": true,
      "categories": [
        "sandwiches"
      ],
      "categoryOrders": [],
      "description": "Morceaux de poulet marines et grilles",
      "displayOrder": 12,
      "image": "",
      "name": "Brochette Poulet",
      "popular": false,
      "price": 7.5,
      "priceWithFries": 9.5
    },
    {
      "_creationTime": 1771850446637.127,
      "_id": "j97dwbte88hh85byxdjcjdc28181qge7",
      "active": true,
      "categories": [
        "sandwiches"
      ],
      "categoryOrders": [],
      "description": "Morceaux de veau marines et grilles",
      "displayOrder": 13,
      "image": "",
      "name": "Brochette Veau",
      "popular": false,
      "price": 9,
      "priceWithFries": 11
    },
    {
      "_creationTime": 1771850446637.1272,
      "_id": "j97dwagfzkqr9120n9bg86df4981q16h",
      "active": true,
      "categories": [
        "sandwiches"
      ],
      "categoryOrders": [],
      "description": "Morceaux d'agneau marines et grilles",
      "displayOrder": 14,
      "image": "",
      "name": "Brochette Agneau",
      "popular": false,
      "price": 9,
      "priceWithFries": 11
    },
    {
      "_creationTime": 1771850446637.1274,
      "_id": "j97be1f9j49nwegv6jdmb9cj5d81qfd5",
      "active": true,
      "categories": [
        "sandwiches"
      ],
      "categoryOrders": [],
      "description": "Pain brioche, poulet pane, crudites et sauce",
      "displayOrder": 15,
      "image": "",
      "name": "Chickenburger",
      "popular": false,
      "price": 7,
      "priceWithFries": 9
    },
    {
      "_creationTime": 1771850446637.1277,
      "_id": "j97f9fh7rjweyhf84n7r69rcgx81pvaf",
      "active": true,
      "categories": [
        "sandwiches-vegetarien"
      ],
      "categoryOrders": [],
      "description": "",
      "displayOrder": 16,
      "image": "",
      "name": "Sandwich Végétarien",
      "popular": false,
      "price": 5.5,
      "priceWithFries": 7.5
    },
    {
      "_creationTime": 1771850446637.128,
      "_id": "j975v4ktns043y1ayqc5t343hn81pjxf",
      "active": true,
      "categories": [
        "sandwiches-vegetarien"
      ],
      "categoryOrders": [],
      "description": "",
      "displayOrder": 17,
      "image": "",
      "name": "Pain Frites",
      "popular": false,
      "price": 6
    },
    {
      "_creationTime": 1771850446637.1282,
      "_id": "j976tb7d2yfjr5ttnqt9pvtmts81qyed",
      "active": true,
      "categories": [
        "sandwiches-vegetarien"
      ],
      "categoryOrders": [],
      "description": "",
      "displayOrder": 18,
      "image": "",
      "name": "Pan Bagnat",
      "popular": false,
      "price": 6,
      "priceWithFries": 8
    },
    {
      "_creationTime": 1771850446637.1284,
      "_id": "j97cx2k1ytdq21jehrkk45fd0181pgyj",
      "active": true,
      "categories": [
        "sandwiches-vegetarien"
      ],
      "categoryOrders": [],
      "description": "",
      "displayOrder": 19,
      "image": "",
      "name": "Fish",
      "popular": false,
      "price": 6.5,
      "priceWithFries": 8.5
    },
    {
      "_creationTime": 1771850446637.1287,
      "_id": "j9769640fr7rg39zfxn958e75n81pe0j",
      "active": true,
      "categories": [
        "sandwiches-vegetarien"
      ],
      "categoryOrders": [],
      "description": "",
      "displayOrder": 20,
      "image": "",
      "name": "Sandwich Falafels",
      "popular": false,
      "price": 6.5,
      "priceWithFries": 8.5
    },
    {
      "_creationTime": 1771850446637.129,
      "_id": "j97drerc2xfzj23m7z80hckj2n81qa8s",
      "active": true,
      "categories": [
        "assiettes"
      ],
      "categoryOrders": [],
      "description": "Au choix: riz, pates, frites ou ble",
      "displayOrder": 21,
      "image": "",
      "name": "Assiette Kebab",
      "popular": true,
      "price": 13
    },
    {
      "_creationTime": 1771850446637.1292,
      "_id": "j975xfmpesj85qbkrbwnb27w6s81pwvb",
      "active": true,
      "categories": [
        "assiettes"
      ],
      "categoryOrders": [],
      "description": "Poulet grille avec accompagnement au choix",
      "displayOrder": 22,
      "image": "",
      "name": "Assiette Steak Haché",
      "popular": false,
      "price": 14
    },
    {
      "_creationTime": 1771850446637.1294,
      "_id": "j9759be9epekvy11vzj1ajsv8x81p8hx",
      "active": true,
      "categories": [
        "assiettes"
      ],
      "categoryOrders": [],
      "description": "Assortiment special du chef avec accompagnements",
      "displayOrder": 23,
      "image": "",
      "name": "Assiette Cheese",
      "popular": true,
      "price": 17
    },
    {
      "_creationTime": 1771850446637.1296,
      "_id": "j9721tnew3d74v0wshf1skxxqn81phq9",
      "active": true,
      "categories": [
        "assiettes"
      ],
      "categoryOrders": [],
      "description": "Tenders croustillants avec accompagnement",
      "displayOrder": 24,
      "image": "",
      "name": "Assiette Falafels",
      "popular": false,
      "price": 14
    },
    {
      "_creationTime": 1771850446637.13,
      "_id": "j975xdk7ak1trf26e0bd2jbreh81q5ww",
      "active": true,
      "categories": [
        "assiettes"
      ],
      "categoryOrders": [],
      "description": "Falafels maison sans viande avec accompagnement",
      "displayOrder": 25,
      "image": "",
      "name": "Assiette Tenders",
      "popular": false,
      "price": 13
    },
    {
      "_creationTime": 1771850446637.1301,
      "_id": "j97fw6gzpbcpv58jambth1yhgs81p4tg",
      "active": true,
      "categories": [
        "assiettes"
      ],
      "categoryOrders": [],
      "description": "Falafels maison sans viande avec accompagnement",
      "displayOrder": 26,
      "image": "",
      "name": "Assiette Cordon Bleu",
      "popular": false,
      "price": 13
    },
    {
      "_creationTime": 1771850446637.1304,
      "_id": "j973pa33qx2t7h3zq6y5eg9avs81p41b",
      "active": true,
      "categories": [
        "assiettes"
      ],
      "categoryOrders": [],
      "description": "Falafels maison sans viande avec accompagnement",
      "displayOrder": 27,
      "image": "",
      "name": "Assiette Merguez",
      "popular": false,
      "price": 13
    },
    {
      "_creationTime": 1771850446637.1306,
      "_id": "j976b5zcamrweyzvmjbyh81fzn81qscd",
      "active": true,
      "categories": [
        "assiettes"
      ],
      "categoryOrders": [],
      "description": "Falafels maison sans viande avec accompagnement",
      "displayOrder": 28,
      "image": "",
      "name": "Assiette du Chef",
      "popular": false,
      "price": 13
    },
    {
      "_creationTime": 1771850446637.1309,
      "_id": "j977cjvjmg8zy4s7j4w9dmkh3n81pas9",
      "active": true,
      "categories": [
        "assiettes"
      ],
      "categoryOrders": [],
      "description": "Falafels maison sans viande avec accompagnement",
      "displayOrder": 29,
      "image": "",
      "name": "Assiette Adana",
      "popular": false,
      "price": 13
    },
    {
      "_creationTime": 1771850446637.131,
      "_id": "j97am3sxc6hwtj10ww2vt75xk581q5b8",
      "active": true,
      "categories": [
        "assiettes"
      ],
      "categoryOrders": [],
      "description": "Falafels maison sans viande avec accompagnement",
      "displayOrder": 30,
      "image": "",
      "name": "Assiette Saucisse Turque",
      "popular": false,
      "price": 13
    },
    {
      "_creationTime": 1771850446637.1313,
      "_id": "j975nxb9trjnx61228fbd68s2n81qgzj",
      "active": true,
      "categories": [
        "assiettes"
      ],
      "categoryOrders": [],
      "description": "Falafels maison sans viande avec accompagnement",
      "displayOrder": 31,
      "image": "",
      "name": "Assiette Kofte",
      "popular": false,
      "price": 13
    },
    {
      "_creationTime": 1771850446637.1316,
      "_id": "j97bn1ashana3t9zywsvgm7djx81q5h2",
      "active": true,
      "categories": [
        "assiettes"
      ],
      "categoryOrders": [],
      "description": "Falafels maison sans viande avec accompagnement",
      "displayOrder": 32,
      "image": "",
      "name": "Assiette Agneau",
      "popular": false,
      "price": 13
    },
    {
      "_creationTime": 1771850446637.1318,
      "_id": "j97ca86sqsgknsetm1y0ds3gq181pkvb",
      "active": true,
      "categories": [
        "assiettes"
      ],
      "categoryOrders": [],
      "description": "Falafels maison sans viande avec accompagnement",
      "displayOrder": 33,
      "image": "",
      "name": "Assiette Veau",
      "popular": false,
      "price": 13
    },
    {
      "_creationTime": 1771850446637.132,
      "_id": "j971zyf8dr8w0x4pynghc2yw8181p9re",
      "active": true,
      "categories": [
        "assiettes"
      ],
      "categoryOrders": [],
      "description": "Falafels maison sans viande avec accompagnement",
      "displayOrder": 34,
      "image": "",
      "name": "Assiette Poulet",
      "popular": false,
      "price": 13
    },
    {
      "_creationTime": 1771850446637.1323,
      "_id": "j97efxd3r3w1f3f14d0qv6h73n81qhkc",
      "active": true,
      "categories": [
        "tacos"
      ],
      "categoryOrders": [],
      "description": "Viande au choix, frites, fromage et sauce",
      "displayOrder": 35,
      "image": "",
      "name": "Tacos 1 Viande",
      "popular": false,
      "price": 8
    },
    {
      "_creationTime": 1771850446637.1326,
      "_id": "j97fw864y5cs89bxhzr16b6dxd81p8wc",
      "active": true,
      "categories": [
        "tacos"
      ],
      "categoryOrders": [],
      "description": "2 viandes au choix, frites, fromage et sauce",
      "displayOrder": 36,
      "image": "",
      "name": "Tacos 2 Viandes",
      "popular": true,
      "price": 10
    },
    {
      "_creationTime": 1771850446637.1328,
      "_id": "j970myfg5cezwy64p3f57s1fn181qq5s",
      "active": true,
      "categories": [
        "tacos"
      ],
      "categoryOrders": [],
      "description": "3 viandes au choix, frites, fromage et sauce",
      "displayOrder": 37,
      "image": "",
      "name": "Tacos 3 Viandes",
      "popular": false,
      "price": 12
    },
    {
      "_creationTime": 1771850446637.133,
      "_id": "j971m9szjh4ftw1qap6qxgktmx81q3nr",
      "active": true,
      "categories": [
        "durum"
      ],
      "categoryOrders": [],
      "description": "Galette fine, viande kebab, salade et sauce",
      "displayOrder": 38,
      "image": "https://industrious-zebra-835.convex.cloud/api/storage/78d64a3a-c2b6-47de-ba16-3786a4b9638e",
      "name": "Durum Kebab",
      "popular": true,
      "price": 7.5
    },
    {
      "_creationTime": 1771850446637.1333,
      "_id": "j97cy6gssg4ehq5nz896h3djzs81pjzb",
      "active": true,
      "categories": [
        "durum"
      ],
      "categoryOrders": [],
      "description": "Galette fine, poulet grille, crudites",
      "displayOrder": 39,
      "image": "",
      "name": "Durum Poulet",
      "popular": false,
      "price": 8
    },
    {
      "_creationTime": 1771850446637.1335,
      "_id": "j97fqwqm69pzqd11z21amjsgqd81qxdn",
      "active": true,
      "categories": [
        "durum"
      ],
      "categoryOrders": [],
      "description": "Galette fine, tenders croustillants, sauce",
      "displayOrder": 40,
      "image": "",
      "name": "Durum Tenders",
      "popular": false,
      "price": 8
    },
    {
      "_creationTime": 1771850446637.1338,
      "_id": "j97b5km7n2n5fyv3mb6kys3ghh81psy4",
      "active": true,
      "categories": [
        "durum"
      ],
      "categoryOrders": [],
      "description": "Version XXL de notre durum",
      "displayOrder": 41,
      "image": "",
      "name": "Maxi Durum",
      "popular": false,
      "price": 10
    },
    {
      "_creationTime": 1771850446637.134,
      "_id": "j97b0ebcp5agn8z1d3ycvqmf6h81p1ht",
      "active": true,
      "categories": [
        "pizzas"
      ],
      "categoryOrders": [],
      "description": "Wrap pizza garni de viande kebab",
      "displayOrder": 42,
      "image": "",
      "name": "Pizza Kebab",
      "popular": true,
      "price": 8
    },
    {
      "_creationTime": 1771850446637.1343,
      "_id": "j9733704ty03nbwqmbadq7g9j181pyrf",
      "active": true,
      "categories": [
        "pizzas"
      ],
      "categoryOrders": [],
      "description": "Wrap pizza aux saveurs turques",
      "displayOrder": 43,
      "image": "",
      "name": "Pizza Turque",
      "popular": false,
      "price": 6.5
    },
    {
      "_creationTime": 1771850446637.1345,
      "_id": "j975jkp7zevccnwgbhy7gtb8r581qybm",
      "active": true,
      "categories": [
        "pizzas"
      ],
      "categoryOrders": [],
      "description": "Wrap pizza garni de poulet",
      "displayOrder": 44,
      "image": "",
      "name": "Pizza Poulet",
      "popular": false,
      "price": 8.5
    },
    {
      "_creationTime": 1771850446637.1348,
      "_id": "j971rf50nre3s548p5tefw6r1581pgp4",
      "active": true,
      "categories": [
        "barquettes"
      ],
      "categoryOrders": [],
      "description": "Frites fraiches et croustillantes",
      "displayOrder": 45,
      "image": "",
      "name": "Barquette Frites",
      "popular": false,
      "price": 3.5
    },
    {
      "_creationTime": 1771850446637.135,
      "_id": "j9729rkr40dtvps6knn39rqvkd81pscz",
      "active": true,
      "categories": [
        "barquettes"
      ],
      "categoryOrders": [],
      "description": "Barquette de viande kebab seule",
      "displayOrder": 46,
      "image": "",
      "name": "Barquette Viande Kebab",
      "popular": false,
      "price": 7
    },
    {
      "_creationTime": 1771850446637.1353,
      "_id": "j97ept9r9k6n4mwmd3558by88d81qt8p",
      "active": true,
      "categories": [
        "barquettes"
      ],
      "categoryOrders": [],
      "description": "Barquette de viande kebab seule",
      "displayOrder": 47,
      "image": "",
      "name": "Barquette Viande Poulet",
      "popular": false,
      "price": 7
    },
    {
      "_creationTime": 1771850446637.1355,
      "_id": "j97238301skaredxffksvbptv981qryh",
      "active": true,
      "categories": [
        "barquettes"
      ],
      "categoryOrders": [],
      "description": "Barquette de viande kebab seule",
      "displayOrder": 48,
      "image": "",
      "name": "Barquette Viande Blé",
      "popular": false,
      "price": 7
    },
    {
      "_creationTime": 1771850446637.1357,
      "_id": "j97fv1vher1jfpga72ptzd99dd81q8e4",
      "active": true,
      "categories": [
        "barquettes"
      ],
      "categoryOrders": [],
      "description": "Nuggets de poulet croustillants (x4, x6, x9, x12)",
      "displayOrder": 49,
      "image": "",
      "name": "Nuggets",
      "popular": false,
      "price": 4
    },
    {
      "_creationTime": 1771850446637.136,
      "_id": "j970tat5trmetjhzds49vaa35d81q9j0",
      "active": true,
      "categories": [
        "barquettes"
      ],
      "categoryOrders": [],
      "description": "Tenders de poulet panes (4.50, 6.50, 10.00, 13.50)",
      "displayOrder": 50,
      "image": "",
      "name": "Mozza Sticks",
      "popular": false,
      "price": 4.5
    },
    {
      "_creationTime": 1771850446637.1362,
      "_id": "j97d6ngwcyem61a50tqnyzdx3x81q3qv",
      "active": true,
      "categories": [
        "barquettes"
      ],
      "categoryOrders": [],
      "description": "Tenders de poulet panes (4.50, 6.50, 10.00, 13.50)",
      "displayOrder": 51,
      "image": "",
      "name": "Box Poulet",
      "popular": false,
      "price": 4.5
    },
    {
      "_creationTime": 1771850446637.1365,
      "_id": "j970831vykk6dn3bf13e1x4qkd81qpef",
      "active": true,
      "categories": [
        "box"
      ],
      "categoryOrders": [],
      "description": "Box avec viande kebab",
      "displayOrder": 52,
      "image": "",
      "name": "Box Kebab",
      "popular": false,
      "price": 7.5
    },
    {
      "_creationTime": 1771850446637.1367,
      "_id": "j9738n2pn3w64nan36mnk7nn0x81pjhp",
      "active": true,
      "categories": [
        "box"
      ],
      "categoryOrders": [],
      "description": "Box avec poulet grille",
      "displayOrder": 53,
      "image": "",
      "name": "Box Poulet",
      "popular": false,
      "price": 8.5
    },
    {
      "_creationTime": 1771850446637.137,
      "_id": "j97f35ctbd9ka3xbf9070dtpw981q888",
      "active": true,
      "categories": [
        "salades"
      ],
      "categoryOrders": [],
      "description": "Salade fraiche avec fromage feta",
      "displayOrder": 54,
      "image": "",
      "name": "Salade Feta",
      "popular": false,
      "price": 7.5
    },
    {
      "_creationTime": 1771850446637.1372,
      "_id": "j97djxsvyxvq6rkwenbr5kqh2n81qdte",
      "active": true,
      "categories": [
        "salades"
      ],
      "categoryOrders": [],
      "description": "Salade composee au thon",
      "displayOrder": 55,
      "image": "",
      "name": "Salade Thon",
      "popular": false,
      "price": 9
    },
    {
      "_creationTime": 1771850446637.1375,
      "_id": "j97d8799btn6twbm1vc481yxwh81qcbw",
      "active": true,
      "categories": [
        "salades"
      ],
      "categoryOrders": [],
      "description": "Salade fraiche avec poulet grille",
      "displayOrder": 56,
      "image": "",
      "name": "Salade Poulet",
      "popular": false,
      "price": 9
    },
    {
      "_creationTime": 1771850446637.1377,
      "_id": "j970693jp5nk8mnktkbc4j5gy181q3bf",
      "active": true,
      "categories": [
        "salades"
      ],
      "categoryOrders": [],
      "description": "Salade fraiche avec poulet grille",
      "displayOrder": 57,
      "image": "",
      "name": "Salade Tenders",
      "popular": false,
      "price": 9
    },
    {
      "_creationTime": 1771850446637.138,
      "_id": "j976c9arsr7xbxb2ztbtta3dmn81qcv7",
      "active": true,
      "categories": [
        "bowls"
      ],
      "categoryOrders": [],
      "description": "Viandes au choix: kebab, brochettes, steak, kofte",
      "displayOrder": 58,
      "image": "",
      "name": "Bowl Riz",
      "popular": true,
      "price": 9.5
    },
    {
      "_creationTime": 1771850446637.1382,
      "_id": "j977yz3m02rsa6awk3jmee8apx81pcxs",
      "active": true,
      "categories": [
        "bowls"
      ],
      "categoryOrders": [],
      "description": "Viandes au choix: kebab, brochettes, steak, kofte",
      "displayOrder": 59,
      "image": "",
      "name": "Bowl Pates",
      "popular": true,
      "price": 9.5
    },
    {
      "_creationTime": 1771850446637.1384,
      "_id": "j972r9ag676np7yqzf81mvyzyn81prz9",
      "active": true,
      "categories": [
        "kapsalon"
      ],
      "categoryOrders": [],
      "description": "Frites, fromage, salade et viande au choix",
      "displayOrder": 60,
      "image": "",
      "name": "Kapsalon 1 Viande",
      "popular": true,
      "price": 10
    },
    {
      "_creationTime": 1771850446637.1387,
      "_id": "j974yqz7syfw6hxcbbcq4tbznn81pfqn",
      "active": true,
      "categories": [
        "kapsalon"
      ],
      "categoryOrders": [],
      "description": "Frites, fromage, salade et 2 viandes au choix",
      "displayOrder": 61,
      "image": "",
      "name": "Kapsalon 2 Viandes",
      "popular": true,
      "price": 12
    },
    {
      "_creationTime": 1771850446637.139,
      "_id": "j970c58cffkvct6ha746grf5pd81pfe0",
      "active": true,
      "categories": [
        "desserts"
      ],
      "categoryOrders": [],
      "description": "Dessert italien traditionnel",
      "displayOrder": 62,
      "image": "",
      "name": "Tiramisu",
      "popular": false,
      "price": 3.5
    },
    {
      "_creationTime": 1771850446637.1392,
      "_id": "j9704ewsc9htv2xwm7gm7sn3ah81pz7y",
      "active": true,
      "categories": [
        "desserts"
      ],
      "categoryOrders": [],
      "description": "Les 3 pieces",
      "displayOrder": 63,
      "image": "",
      "name": "Baklava",
      "popular": true,
      "price": 4
    },
    {
      "_creationTime": 1771850446637.1394,
      "_id": "j97b9gz1v8bdjhszq3vgdveybn81qkv7",
      "active": true,
      "categories": [
        "boissons"
      ],
      "categoryOrders": [],
      "description": "Boisson gazeuse 33cl",
      "displayOrder": 64,
      "image": "",
      "name": "Soft 33cl",
      "popular": false,
      "price": 2
    },
    {
      "_creationTime": 1771850446637.1396,
      "_id": "j9761r72f8t7ht4wa1wy3hj6gs81pmww",
      "active": true,
      "categories": [
        "boissons"
      ],
      "categoryOrders": [],
      "description": "Boisson gazeuse 50cl",
      "displayOrder": 65,
      "image": "",
      "name": "Soft 50cl",
      "popular": false,
      "price": 3.5
    },
    {
      "_creationTime": 1771850446637.14,
      "_id": "j971qytsf0hwcf8sh22pfa53gd81qcwv",
      "active": true,
      "categories": [
        "boissons"
      ],
      "categoryOrders": [],
      "description": "Boisson gazeuse 1,5L",
      "displayOrder": 66,
      "image": "",
      "name": "Soft 1,5L",
      "popular": false,
      "price": 4.5
    },
    {
      "_creationTime": 1771850446637.1401,
      "_id": "j974k5ajcczpf3nfreecwcaj2h81q1dr",
      "active": true,
      "categories": [
        "boissons"
      ],
      "categoryOrders": [],
      "description": "Boisson energisante",
      "displayOrder": 67,
      "image": "",
      "name": "Red Bull",
      "popular": false,
      "price": 3.5
    },
    {
      "_creationTime": 1771850446637.1404,
      "_id": "j9711mnntqsgf4yp99kr3m7ffh81q1we",
      "active": true,
      "categories": [
        "boissons"
      ],
      "description": "Eau minerale",
      "displayOrder": 68,
      "image": "https://images.pexels.com/photos/1000084/pexels-photo-1000084.jpeg?auto=compress&cs=tinysrgb&w=600",
      "name": "Eau 50cl",
      "price": 1.5
    },
    {
      "_creationTime": 1771850446637.1406,
      "_id": "j97cbvv2rg1fhtsjxqr89sp37581pzy3",
      "active": true,
      "categories": [
        "boissons"
      ],
      "description": "The chaud",
      "displayOrder": 69,
      "image": "https://images.pexels.com/photos/1638280/pexels-photo-1638280.jpeg?auto=compress&cs=tinysrgb&w=600",
      "name": "The",
      "price": 1.5
    },
    {
      "_creationTime": 1771850446637.1409,
      "_id": "j973bmwzt3qd6zmpmh5ywkd9gh81qvqs",
      "active": true,
      "categories": [
        "boissons"
      ],
      "description": "Cafe expresso",
      "displayOrder": 70,
      "image": "https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg?auto=compress&cs=tinysrgb&w=600",
      "name": "Cafe",
      "price": 1.5
    }
  ],
  "restaurantInfo": [
    {
      "_creationTime": 1771850450061.02,
      "_id": "k1778wp9h8yk7x2a7sa0zz1rc981pvsy",
      "address": "11 Rue nationale, 57190 Florange",
      "defaultDeliveryFee": 0,
      "deliveryEnabled": true,
      "deliveryFees": [],
      "email": "contact@karadeniz.fr",
      "holidays": [],
      "hours": [
        {
          "day": "Lundi",
          "time": "11h00 - 15h00 et 17h00 - 00h00"
        },
        {
          "day": "Mardi",
          "time": "11h00 - 15h00 et 17h00 - 00h00"
        },
        {
          "day": "Mercredi",
          "time": "11h00 - 15h00 et 17h00 - 00h00"
        },
        {
          "day": "Jeudi",
          "time": "11h00 - 15h00 et 17h00 - 00h00"
        },
        {
          "day": "Vendredi",
          "time": "11h00 - 15h00 et 17h00 - 00h00"
        },
        {
          "day": "Samedi",
          "time": "11h00 - 15h00 et 17h00 - 00h00"
        },
        {
          "day": "Dimanche",
          "time": "17h00 - 00h00"
        }
      ],
      "key": "main",
      "minimumAdvanceNotice": 30,
      "phone": "03 82 58 13 39",
      "pickupEnabled": true,
      "socialLinks": {
        "facebook": "https://facebook.com/karadeniz",
        "instagram": "https://instagram.com/karadeniz",
        "twitter": "https://twitter.com/karadeniz"
      }
    }
  ],
  "reviews": [
    {
      "_creationTime": 1770198906313.9846,
      "_id": "k970ftzja4cn0wytxnjefk450980hdn0",
      "active": true,
      "comment": "Prix plus que raisonnable au regard de la quantité et de la qualité des sandwichs. Sur place comme à emporter, tout est toujours bien.",
      "date": "15 Janvier 2025",
      "name": "Audrey",
      "rating": 5
    },
    {
      "_creationTime": 1770198906313.9849,
      "_id": "k9737a1e1sv823sfgn8haeanqx80hh67",
      "active": true,
      "comment": "Un bon petit restaurant turc avec de grandes plages horaires pour venir manger ou emporter différentes spécialités provenant de la région de la mer noire...et d autres plus classiques.",
      "date": "22 Janvier 2025",
      "name": "Eric",
      "rating": 5
    },
    {
      "_creationTime": 1770198906313.985,
      "_id": "k9765a8dcw9z6fmr3gcd5s0chs80g7vx",
      "active": true,
      "comment": "C'est simple. c'est le meilleur kebab que j'ai pu manger depuis 20 ans! J'habite dans le sud et lorsque je remonte dans l'est, j en profite un max. Je les adore!!!!!",
      "date": "28 Janvier 2025",
      "name": "Jean Dartois",
      "rating": 5
    },
    {
      "_creationTime": 1770198906313.9854,
      "_id": "k970k30vqx0eyspfp9efmt91p980gnxt",
      "active": true,
      "comment": "Personnel agréable, rapide.. Jamais d'oublies dans mes commandes. Repas chaud 👍, prix raisonnables vu la crise et eux n'ont pas augmenter le prix fortement. Malgré les charges. Bravo c super bon =>. Je reviendrai.",
      "date": "30 Janvier 2025",
      "name": "Marc",
      "rating": 5
    },
    {
      "_creationTime": 1771850451793.2666,
      "_id": "k970b15sh97ktn0azs2q6hsqxh81pab6",
      "active": true,
      "comment": "Prix plus que raisonnable au regard de la quantité et de la qualité des sandwichs. Sur place comme à emporter, tout est toujours bien.",
      "date": "15 Janvier 2025",
      "name": "Audrey",
      "rating": 5
    },
    {
      "_creationTime": 1771850451793.2668,
      "_id": "k97bqnqrn75pb84ne0f7f8sbk181pn9k",
      "active": true,
      "comment": "Un bon petit restaurant turc avec de grandes plages horaires pour venir manger ou emporter différentes spécialités provenant de la région de la mer noire...et d autres plus classiques.",
      "date": "22 Janvier 2025",
      "name": "Eric",
      "rating": 5
    },
    {
      "_creationTime": 1771850451793.267,
      "_id": "k975vbk92p44yx48rcpn24wtds81p2zd",
      "active": true,
      "comment": "C'est simple. c'est le meilleur kebab que j'ai pu manger depuis 20 ans! J'habite dans le sud et lorsque je remonte dans l'est, j en profite un max. Je les adore!!!!!",
      "date": "28 Janvier 2025",
      "name": "Jean Dartois",
      "rating": 5
    },
    {
      "_creationTime": 1771850451793.2673,
      "_id": "k979y16k5pe3wksq2k115wygpn81qdhk",
      "active": true,
      "comment": "Personnel agréable, rapide.. Jamais d'oublies dans mes commandes. Repas chaud 👍, prix raisonnables vu la crise et eux n'ont pas augmenter le prix fortement. Malgré les charges. Bravo c super bon =>. Je reviendrai.",
      "date": "30 Janvier 2025",
      "name": "Marc",
      "rating": 5
    }
  ],
  "toppingCategories": [
    {
      "_creationTime": 1771850443780.0383,
      "_id": "jn72fe4mqhac5s784a9xntydh581pbsc",
      "active": true,
      "categoryId": "sauces",
      "displayOrder": 0,
      "maxSelection": 2,
      "minSelection": 0,
      "name": "Sauces"
    },
    {
      "_creationTime": 1771850443780.0386,
      "_id": "jn70zsxggdmjncvn67y0jrzqms81pt2q",
      "active": true,
      "categoryId": "crudites",
      "displayOrder": 1,
      "minSelection": 0,
      "name": "Crudités"
    },
    {
      "_creationTime": 1771850443780.0388,
      "_id": "jn71e0yxjwfm1xbh76p3193b9n81p4q3",
      "active": true,
      "categoryId": "supplements",
      "displayOrder": 2,
      "minSelection": 0,
      "name": "Suppléments"
    },
    {
      "_creationTime": 1771850443780.039,
      "_id": "jn7apfa0jysyvdys0a74w3w0n581pmsq",
      "active": true,
      "categoryId": "viandes",
      "displayOrder": 3,
      "maxSelection": 3,
      "minSelection": 0,
      "name": "Viandes"
    }
  ],
  "toppings": [
    {
      "_creationTime": 1771850445164.4702,
      "_id": "jh73fdqqdg9pdvr8fwyf750tax81qg7c",
      "active": true,
      "categoryId": "sauces",
      "displayOrder": 0,
      "name": "Sauce Blanche",
      "toppingId": "sauce-blanche"
    },
    {
      "_creationTime": 1771850445164.4705,
      "_id": "jh7bq0asakq2enmsw6vzarmred81pd5e",
      "active": true,
      "categoryId": "sauces",
      "displayOrder": 1,
      "name": "Sauce Andalouse",
      "toppingId": "sauce-andalouse"
    },
    {
      "_creationTime": 1771850445164.4707,
      "_id": "jh79qp3efxy3sky1d0nprggfh181qkbp",
      "active": true,
      "categoryId": "sauces",
      "displayOrder": 2,
      "name": "Sauce Barbecue",
      "toppingId": "sauce-barbecue"
    },
    {
      "_creationTime": 1771850445164.471,
      "_id": "jh7ezerq7trjk07d8w80fvdbe181qybh",
      "active": true,
      "categoryId": "sauces",
      "displayOrder": 3,
      "name": "Sauce Algérienne",
      "toppingId": "sauce-algerienne"
    },
    {
      "_creationTime": 1771850445164.4712,
      "_id": "jh7dbqbcmqycqwa6d8c8hh9za581pv9p",
      "active": true,
      "categoryId": "sauces",
      "displayOrder": 4,
      "name": "Sauce Samurai",
      "toppingId": "sauce-samurai"
    },
    {
      "_creationTime": 1771850445164.4714,
      "_id": "jh730kqdm3pjzyzg7049eywgn981qtvz",
      "active": true,
      "categoryId": "sauces",
      "displayOrder": 5,
      "name": "Ketchup",
      "toppingId": "sauce-ketchup"
    },
    {
      "_creationTime": 1771850445164.4717,
      "_id": "jh7f3gce8df0ghew1hjrjjs4g981pgqf",
      "active": true,
      "categoryId": "sauces",
      "displayOrder": 6,
      "name": "Mayonnaise",
      "toppingId": "sauce-mayo"
    },
    {
      "_creationTime": 1771850445164.472,
      "_id": "jh72jj8g6m7x8ay70mvvqe5xd181qb85",
      "active": true,
      "categoryId": "sauces",
      "displayOrder": 7,
      "name": "Sauce Curry",
      "toppingId": "sauce-curry"
    },
    {
      "_creationTime": 1771850445164.4722,
      "_id": "jh7cks5svr1p6nwajs1bt2b3kd81px5w",
      "active": true,
      "categoryId": "sauces",
      "displayOrder": 8,
      "name": "Sauce Biggy",
      "toppingId": "sauce-biggy"
    },
    {
      "_creationTime": 1771850445164.4724,
      "_id": "jh70wxm2t3sj0agz52zs5bpfm181p5dd",
      "active": true,
      "categoryId": "sauces",
      "displayOrder": 9,
      "name": "Moutarde",
      "toppingId": "sauce-moutarde"
    },
    {
      "_creationTime": 1771850445164.4727,
      "_id": "jh71kgvfpxwpxh332713y149rd81qfr5",
      "active": true,
      "categoryId": "sauces",
      "displayOrder": 10,
      "name": "Harissa",
      "toppingId": "sauce-harissa"
    },
    {
      "_creationTime": 1771850445164.473,
      "_id": "jh79pnyyazcymg66x95nq4j65581qkj5",
      "active": true,
      "categoryId": "crudites",
      "displayOrder": 0,
      "name": "Salade",
      "toppingId": "salade"
    },
    {
      "_creationTime": 1771850445164.4731,
      "_id": "jh79pzzhxrsstzdqa1j0cdsjss81peyf",
      "active": true,
      "categoryId": "crudites",
      "displayOrder": 1,
      "name": "Tomate",
      "toppingId": "tomate"
    },
    {
      "_creationTime": 1771850445164.4734,
      "_id": "jh750xmpzkx2yj21s5ykbyhmdx81pvr1",
      "active": true,
      "categoryId": "crudites",
      "displayOrder": 2,
      "name": "Oignon",
      "toppingId": "oignon"
    },
    {
      "_creationTime": 1771850445164.4736,
      "_id": "jh75tsvf22d2np9m7n84q7s3x981qscz",
      "active": true,
      "categoryId": "crudites",
      "displayOrder": 3,
      "name": "Chou Rouge",
      "toppingId": "chou-rouge"
    },
    {
      "_creationTime": 1771850445164.4739,
      "_id": "jh78fy1z517yj18xytjwf0zc9n81qaxm",
      "active": true,
      "categoryId": "supplements",
      "displayOrder": 0,
      "name": "cheddar",
      "price": 1,
      "toppingId": "cheddar"
    },
    {
      "_creationTime": 1771850445164.474,
      "_id": "jh78955cc9g9pys9qv65dcvpen81q425",
      "active": true,
      "categoryId": "supplements",
      "displayOrder": 1,
      "name": "Feta",
      "price": 1,
      "toppingId": "feta"
    },
    {
      "_creationTime": 1771850445164.4744,
      "_id": "jh754kpp6572pm0as6qx65dmkn81py22",
      "active": true,
      "categoryId": "viandes",
      "displayOrder": 0,
      "name": "Poulet",
      "toppingId": "poulet"
    },
    {
      "_creationTime": 1771850445164.4746,
      "_id": "jh772pw85zkg3xx7axnfzgtyhn81qh3k",
      "active": true,
      "categoryId": "viandes",
      "displayOrder": 1,
      "name": "Viande Hachée",
      "toppingId": "viande-hachee"
    },
    {
      "_creationTime": 1771850445164.4749,
      "_id": "jh78aa4rrhjavd9m4jnjfxzxkn81qnwq",
      "active": true,
      "categoryId": "viandes",
      "displayOrder": 2,
      "name": "Mergez",
      "toppingId": "mergez"
    },
    {
      "_creationTime": 1771850445164.475,
      "_id": "jh7cf54bfvt6etb6wm073826fs81q5bt",
      "active": true,
      "categoryId": "viandes",
      "displayOrder": 3,
      "name": "Kebab",
      "toppingId": "kebab"
    },
    {
      "_creationTime": 1771850445164.4753,
      "_id": "jh7e01r0vqqpx8n1zbce3ecyyd81qbpa",
      "active": true,
      "categoryId": "viandes",
      "displayOrder": 4,
      "name": "Cordon Bleu",
      "toppingId": "cordon-bleu"
    }
  ]
};
