import { execSync } from 'child_process';
import { writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = join(__dirname, '..');
const OUTPUT_FILE_JSON = join(PROJECT_ROOT, 'convex/data/snapshot.json');
const OUTPUT_FILE_TS = join(PROJECT_ROOT, 'convex/data/snapshot.ts');

console.log('🚀 Exporting current database state from Convex...');

try {
    // Call the exportData query using Convex CLI
    const resultString = execSync('npx convex run seed:exportData', {
        encoding: 'utf-8',
        cwd: PROJECT_ROOT,
    });

    // Function to strip ANSI escape codes
    const stripAnsi = (str) => str.replace(/[\u001b\u009b][[()#;?]*(?:[0-9]{1,4}(?:;[0-9]{0,4})*)?[0-9A-ORZcf-nqry=><]/g, '');

    const cleanResult = stripAnsi(resultString);

    // Convex CLI output might contain some logs or checkmarks before/after the actual JSON
    let data;
    try {
        const firstBrace = cleanResult.indexOf('{');
        const lastBrace = cleanResult.lastIndexOf('}');
        if (firstBrace !== -1 && lastBrace !== -1) {
            const jsonStr = cleanResult.substring(firstBrace, lastBrace + 1);
            data = JSON.parse(jsonStr);
        } else {
            data = JSON.parse(cleanResult);
        }
    } catch (e) {
        console.error('Debug: Cleaned raw output starting with:', cleanResult.substring(0, 500));
        // Try to find the largest valid JSON block if simple extraction fails
        throw new Error('Failed to parse JSON from Convex output. ' + e.message);
    }

    // Ensure the directory exists
    mkdirSync(dirname(OUTPUT_FILE_JSON), { recursive: true });

    // Save to JSON for reference
    writeFileSync(OUTPUT_FILE_JSON, JSON.stringify(data, null, 2));

    // Save to TS for Convex import
    const tsContent = `// This file is auto-generated by scripts/sync-db.mjs
// DO NOT EDIT MANUALLY
export const snapshot: any = ${JSON.stringify(data, null, 2)};
`;
    writeFileSync(OUTPUT_FILE_TS, tsContent);

    console.log(`✅ Database state successfully exported to:`);
    console.log(`   - ${OUTPUT_FILE_JSON}`);
    console.log(`   - ${OUTPUT_FILE_TS}`);
    console.log(`📊 Exported ${data.menuItems?.length || 0} menu items and ${data.menuCategories?.length || 0} categories.`);
} catch (error) {
    console.error('❌ Failed to export database state:');
    console.error(error.message);
    process.exit(1);
}
